# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjectionMoudle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ObjectionMoudle

  target 'ObjectionMoudleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObjectionMoudleUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Objection'
end
